### ISSUE TITLE
Potential Signature Malleability in ECDSA Signature Normalization

### ISSUE THREAD

**Issue by dzikowski** [GalaChain/sdk#133]
Add the following check to ensure the low-S value rule for signature:

```
function normalizeSecp256k1Signature(s: string): Secp256k1Signature {

  ...

  // Additional check for low-S normalization
  if (signatureObj.s.cmp(ecSecp256k1.curve.n.shrn(1)) > 0) {
    throw new InvalidSignatureFormatError("S value is too high");
  }
  return signatureObj;

}
```

**Comment by befitsandpiper** [comment]
The addition of this check looks like it causes some of our tests to fail some tests that should be valid signatures in dtos.spec.ts:
- "should sign and verify signature (edge case - shorter private key with missing trailing 0)"
- "test metamask signatures vs galachain signatures"

**Comment by befitsandpiper** [comment]
I guess we have to change the way we are actually doing signing here to ensure our signatures always are valid with this low-S rule?

**Comment by befitsandpiper** [comment]
you can see my started MR here: https://github.com/GalaChain/sdk/pull/258
