### ISSUE TITLE
Lack of Input Validation for `dto.requests` in `fulfillMintAllowanceRequest`

### ISSUE THREAD

**Issue by Jehosephat** [GalaChain/sdk#155]
Description
The function fulfillMintAllowanceRequest does not perform adequate validation on the dto.requests array, which could lead to unexpected behavior or errors if the input is malformed or contains incorrect data types.

The following code snippet demonstrates the lack of input validation for dto.requests:

const requests = dto.requests;
const requestIds = requests.map((r) => r.id);

for (const [key, values] of Object.entries(reqIdx)) {
  // Assume properties are present and of correct types
  const { collection, category, type, additionalKey } = values[0];
  // Further processing...
}
In this snippet, the function assumes that each element of requests has properties collection, category, type, and additionalKey of type string, and timeKey that can be converted to a BigNumber. There are no checks to verify these assumptions.

Scenario
If an external or internal caller invokes fulfillMintAllowanceRequest with a dto.requests array that contains elements with missing properties or incorrect data types, the function may encounter runtime errors or behave unexpectedly when accessing these properties or performing operations on them.

Recommendation
Implement thorough input validation at the beginning of the fulfillMintAllowanceRequest function to ensure that each element of dto.requests:

Is an object with the expected structure.
Contains all required properties (collection, category, type, additionalKey, and timeKey).
Has properties of the correct data type (strings for collection, category, type, and additionalKey; a string that can be converted to a BigNumber for timeKey).
Additional validations to guarantee logical correctness.
This validation will help prevent runtime errors and ensure that the function behaves as expected, even if the input is malformed or contains incorrect data types.

Locations
fulfillMintAllowance.ts#L48-L48: L48-L48

**Comment by Fuerback** [comment]
The input array of type `FulfillMintAllowanceDto` has only one field `requests: MintRequestDto[]` declared on [allawance.ts](https://github.com/GalaChain/sdk/blob/main/chain-api/src/types/allowance.ts#L367). The type `MintRequestDto` declared on [commons.ts](https://github.com/GalaChain/sdk/blob/main/chain-api/src/types/common.ts#L83) contains all the validations to check if `collection`, `category`, `type`, `additionalKey`, and `timeKey` are not empty.

The only validation missing is checking if `timeKey` can be converted to a BigNumber.
