### ISSUE TITLE
galachain init command error/network test error on Windows

### ISSUE THREAD

**Issue by w3-labs** [GalaChain/sdk#16]
Hi everyone!

I'm testing sdk in windows and when i try to initialize a new project the prompt shows me an error as below

![image](https://github.com/GalaChain/sdk/assets/158523335/18092d1f-d35c-4dda-8200-0b5059f2ea85)

basically this errors tells me that cp command are not recognized by windows

when i try in the git bash prompt it's work fine but even ok when a try to run `npm run network:start` its shows me another error

![image](https://github.com/GalaChain/sdk/assets/158523335/d24d7fc1-f529-48fb-880f-b271a80362c3)

OS: Windows 11
NodeJS: v18.17.0
Npm: 9.6.7

**Comment by Fuerback** [comment]
hey @w3-labs !

here is a 'getting started' documentation that might help you on that.
https://galahackathon.com/v1.0.8/getting-started/

you'll need to use WSL on Windows to initialize the network.

**Comment by w3-labs** [comment]
> hey @w3-labs !
> 
> here is a 'getting started' documentation that might help you on that. https://galahackathon.com/v1.0.8/getting-started/
> 
> you'll need to use WSL on Windows to initialize the network.

After use WSL it works fine! thank you
