### ISSUE TITLE
Inadequate Content Validation in Private and Public Key Normalization

### ISSUE THREAD

**Issue by Jehosephat** [GalaChain/sdk#269]
Both normalizePrivateKey and normalizePublicKey functions in the code validate the length of input strings to determine their format (hex or base64) but do not adequately validate the content. This can lead to accepting strings with the correct length but invalid content.

An attacker could provide strings with the correct length but malformed content for both private and public keys, causing unexpected behavior or security vulnerabilities.

Recommendation
Implement content validation for both private and public keys using regular expressions to ensure strings match the proper hex or base64 format. Update both normalizePrivateKey and normalizePublicKey functions to include these checks. For example:

function isValidHex(input) {
  return /^[0-9a-fA-F]*$/.test(input);
}

function isValidBase64(input) {
  return /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(input);
}

// Update the normalizePrivateKey and normalizePublicKey functions
// to include these validation checks before processing the input.

Certik finding: GDP-01

**Comment by Fuerback** [comment]
Done here https://github.com/GalaChain/sdk/pull/148
