### ISSUE TITLE
FetchBurns Typo

### ISSUE THREAD

**Issue by Jehosephat** [GalaChain/sdk#273]
In the comments above the fetchBurns function in the provided smart contract code. There is a typo in the documentation comments of the fetchBurns function. The word "scenarios" is misspelled as "scensarios". While this does not affect the execution of the code, it may cause confusion or misunderstandings when reading the documentation or comments within the code.

Recommendation
Correct the spelling in the comments to "scenarios". Ensure that documentation and comments are proofread and spell-checked to maintain clarity and professionalism in the codebase.

Certik finding: BGD-01

**Comment by Fuerback** [comment]
I could not find any typo "scensarios" in the SDK documentation. Is it still there?

**Comment by Fuerback** [comment]
Done here https://github.com/GalaChain/sdk/pull/171
