### ISSUE TITLE
Redundant $ in error messages

### ISSUE THREAD

**Issue by dzikowski** [GalaChain/sdk#38]
There are some parts in the code where we have redundant `$` in error message, for instance:

```
super(`BurnTokens failed: ${message}$`, payload);
```

We should scan the code and remove the redundant character.

**Comment by MohitKambli** [comment]
Hello @dzikowski,
Hope you're doing well.
Can I possibly work on this issue?

Thanks and Regards,
Mohit Kambli

**Comment by dzikowski** [comment]
Of course @MohitKambli, we appreciate your contribution 🙂 

Feel free to create a PR from your forked repo, it will trigger automatic tests in GitHub actions (I will need to approve the first run).
