### ISSUE TITLE
Unexpected base64 signature length

### ISSUE THREAD

**Issue by dzikowski** [GalaChain/sdk#89]
For the base64 DER signature: 

```
MEMCH1AjrYbPRI97qFHRbm/URf/BxbV4MVP+obiVt0tlg3UCIEWHQee0ZJHO1iilPLaMLicfSrfrWnOg2ML915+GeCtV
```

our utils serve the error:

```
Unknown signature format. Expected 88, 130, 132, 138, 140, 142, or 144 characters, but got 92
```

however, the signature is correct, because after conversion do hex it has length of 138:

```
3043021f5023ad86cf448f7ba851d16e6fd445ffc1c5b5783153fea1b895b74b6583750220458741e7b46491ced628a53cb68c2e271f4ab7eb5a73a0d8c2fdd79f86782b55
```

Solution:
1. Instead of validating length of base64 string we should convert it to hex, and then check length (recursion, preferably)
2. We should ad a test with the base 64 signature from this issue

**Comment by befitsandpiper** [comment]
As far as I can tell, this der signature works and does not give an error. Is this error old or did it happen recently?

**Comment by befitsandpiper** [comment]
This error doesn't seem to happen anymore on the newest version of sdk. If this error is occuring, make sure to check if the chaincode is updated to the newest version of sdk. Closing ticket.

**Comment by befitsandpiper** [comment]
This error doesn't seem to happen anymore on the newest version of sdk. If this error is occuring, make sure to check if the chaincode is updated to the newest version of sdk. Closing ticket.
